### PR TITLE
Adding exception handling to backoff decorator for ConnectionReset Er…

### PR DESCRIPTION
**Pull request by pbegle**
# Description of change
Tap was failing with `ConnectionResetError`. It appears this is a type of `OSError`. This error was added to the list of exceptions in the backoff decorator. Apparently this error can happen when making many requests to the same endpoint in a loop (as is the case here). It's hard to recreate this error given the small sample size of our test data set but was able to manually test that this would work when encountering this error.

# Manual QA steps
 - As mentioned, recreating this error is difficult. I manually tested this by simulating the error using the following code:
 
```
import socket

import backoff
import requests

URL = "https://google.com"


@backoff.on_exception(backoff.expo, (OSError))
def request(url):
    with requests.Session() as session:
        response = session.request("GET", url)
        print(f"response code: {response.status_code}")

        raise socket.error(104, 'Connection reset by peer')


def main():
    request(URL)


if __name__ == '__main__':
    main()

```
 
This code behaves as expected with backoff retrying the request multiple times.

# Risks
 - It may cause backoff to retry in the event of a different type of `OSError` that may not be recoverable.
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Comment by cosimon** [comment]
Why does this not just catch `ConnectionResetError` if that's what we're trying to catch?

**Comment by pbegle** [comment]
There weren't any clear solutions I could find for this specific error but one of the explanations provided in [this](https://stackoverflow.com/questions/52051989/requests-exceptions-connectionerror-connection-aborted-connectionreseterro) answer seemed to suggest that when making multiple requests via a for loop there could be an instance where you make a request before the server is ready to accept it, causing the `ConnectionResetError`. In that case I think the correct thing to do would be to simply backoff and retry again after a moment instead of trying to catch the error.

**Comment by cosimon** [comment]
Sorry, when I said "catch" I meant put `ConnectionResetError` in the backoff decorator instead of `OSError`, not a literal `try except` block.

**Comment by pbegle** [comment]
Ohh gotcha. I did actually try that. I had done something like this:

```
class ConnectionResetError(OSError):
    pass
```

And passed that in the backoff decorator but was not getting backoff to work as expected when using that custom error. I can't actually reproduce the real error so I was simulating it as shown in the Manual QA section so not sure if that's just a symptom caused by the way that I am simulating the error but thought I would play it safe and leave the more generic `OSError` in the backoff decorator.

**Comment by cosimon** [comment]
The test you have is just raising `OSError` and then catching it (`socket.error` is just an alias for `OSError` https://docs.python.org/3/library/socket.html#socket.error). Can you include the stack trace with the error?

**Comment by pbegle** [comment]
This is the stack trace the tap produce and which I was attempting to recreate:

```
2021-02-02 12:10:53,489Z    tap - INFO HTTP request to "contact_automations" endpoint took 1.464s, returned status code 200
2021-02-02 12:10:53,490Z    tap - ERROR ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2021-02-02 12:10:53,491Z    tap - ERROR response content: b''
2021-02-02 12:10:53,491Z    tap - CRITICAL ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2021-02-02 12:10:53,498Z    tap - Traceback (most recent call last):
2021-02-02 12:10:53,498Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/urllib3/response.py", line 436, in _error_catcher
2021-02-02 12:10:53,498Z    tap -     yield
2021-02-02 12:10:53,498Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/urllib3/response.py", line 763, in read_chunked
2021-02-02 12:10:53,498Z    tap -     self._update_chunk_length()
2021-02-02 12:10:53,498Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/urllib3/response.py", line 693, in _update_chunk_length
2021-02-02 12:10:53,498Z    tap -     line = self._fp.fp.readline()
2021-02-02 12:10:53,498Z    tap -   File "/root/.pyenv/versions/3.5.2/lib/python3.5/socket.py", line 575, in readinto
2021-02-02 12:10:53,498Z    tap -     return self._sock.recv_into(b)
2021-02-02 12:10:53,499Z    tap -   File "/root/.pyenv/versions/3.5.2/lib/python3.5/ssl.py", line 929, in recv_into
2021-02-02 12:10:53,499Z    tap -     return self.read(nbytes, buffer)
2021-02-02 12:10:53,499Z    tap -   File "/root/.pyenv/versions/3.5.2/lib/python3.5/ssl.py", line 791, in read
2021-02-02 12:10:53,499Z    tap -     return self._sslobj.read(len, buffer)
2021-02-02 12:10:53,499Z    tap -   File "/root/.pyenv/versions/3.5.2/lib/python3.5/ssl.py", line 575, in read
2021-02-02 12:10:53,499Z    tap -     v = self._sslobj.read(len, buffer)
2021-02-02 12:10:53,499Z    tap - ConnectionResetError: [Errno 104] Connection reset by peer
2021-02-02 12:10:53,499Z    tap - 
2021-02-02 12:10:53,499Z    tap - During handling of the above exception, another exception occurred:
2021-02-02 12:10:53,499Z    tap - 
2021-02-02 12:10:53,499Z    tap - Traceback (most recent call last):
2021-02-02 12:10:53,499Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/requests/models.py", line 751, in generate
2021-02-02 12:10:53,499Z    tap -     for chunk in self.raw.stream(chunk_size, decode_content=True):
2021-02-02 12:10:53,499Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/urllib3/response.py", line 571, in stream
2021-02-02 12:10:53,499Z    tap -     for line in self.read_chunked(amt, decode_content=decode_content):
2021-02-02 12:10:53,499Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/urllib3/response.py", line 792, in read_chunked
2021-02-02 12:10:53,499Z    tap -     self._original_response.close()
2021-02-02 12:10:53,499Z    tap -   File "/root/.pyenv/versions/3.5.2/lib/python3.5/contextlib.py", line 77, in __exit__
2021-02-02 12:10:53,499Z    tap -     self.gen.throw(type, value, traceback)
2021-02-02 12:10:53,499Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/urllib3/response.py", line 454, in _error_catcher
2021-02-02 12:10:53,499Z    tap -     raise ProtocolError("Connection broken: %r" % e, e)
2021-02-02 12:10:53,500Z    tap - urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2021-02-02 12:10:53,500Z    tap - 
2021-02-02 12:10:53,500Z    tap - During handling of the above exception, another exception occurred:
2021-02-02 12:10:53,500Z    tap - 
2021-02-02 12:10:53,500Z    tap - Traceback (most recent call last):
2021-02-02 12:10:53,500Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_activecampaign/client.py", line 180, in request
2021-02-02 12:10:53,500Z    tap -     response_json = response.json()
2021-02-02 12:10:53,500Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/requests/models.py", line 881, in json
2021-02-02 12:10:53,500Z    tap -     if not self.encoding and self.content and len(self.content) > 3:
2021-02-02 12:10:53,500Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/requests/models.py", line 829, in content
2021-02-02 12:10:53,500Z    tap -     self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
2021-02-02 12:10:53,500Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/requests/models.py", line 754, in generate
2021-02-02 12:10:53,500Z    tap -     raise ChunkedEncodingError(e)
2021-02-02 12:10:53,500Z    tap - requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2021-02-02 12:10:53,500Z    tap - 
2021-02-02 12:10:53,500Z    tap - During handling of the above exception, another exception occurred:
2021-02-02 12:10:53,500Z    tap - 
2021-02-02 12:10:53,500Z    tap - Traceback (most recent call last):
2021-02-02 12:10:53,500Z    tap -   File "tap-env/bin/tap-activecampaign", line 33, in <module>
2021-02-02 12:10:53,500Z    tap -     sys.exit(load_entry_point('tap-activecampaign==0.0.1', 'console_scripts', 'tap-activecampaign')())
2021-02-02 12:10:53,501Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 229, in wrapped
2021-02-02 12:10:53,501Z    tap -     return fnc(*args, **kwargs)
2021-02-02 12:10:53,501Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_activecampaign/__init__.py", line 46, in main
2021-02-02 12:10:53,501Z    tap -     state=state)
2021-02-02 12:10:53,501Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_activecampaign/sync.py", line 373, in sync
2021-02-02 12:10:53,501Z    tap -     selected_streams=selected_streams)
2021-02-02 12:10:53,501Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_activecampaign/sync.py", line 181, in sync_endpoint
2021-02-02 12:10:53,501Z    tap -     endpoint=stream_name)
2021-02-02 12:10:53,501Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_activecampaign/client.py", line 189, in get
2021-02-02 12:10:53,501Z    tap -     return self.request('GET', path=path, api_version=api_version, **kwargs)
2021-02-02 12:10:53,501Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff/_sync.py", line 94, in retry
2021-02-02 12:10:53,501Z    tap -     ret = target(*args, **kwargs)
2021-02-02 12:10:53,501Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 95, in wrapper
2021-02-02 12:10:53,501Z    tap -     return func(*args, **kwargs)
2021-02-02 12:10:53,501Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_activecampaign/client.py", line 184, in request
2021-02-02 12:10:53,501Z    tap -     raise Exception(err)
2021-02-02 12:10:53,501Z    tap - Exception: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2021-02-02 12:10:53,532Z target - INFO Serializing batch with 7100 messages for table contact_automations
2021-02-02 12:10:53,612Z target - INFO Sending batch of 1278708 bytes to https://api.stitchdata.com/v2/import/batch
2021-02-02 12:10:54,884Z target - INFO Requests complete, stopping loop
2021-02-02 12:10:54,939Z   main - INFO Target exited normally with status 0
2021-02-02 12:10:55,452Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobFinished [42] at offset None
2021-02-02 12:10:55,452Z   main - INFO No tunnel subprocess to tear down
2021-02-02 12:10:55,453Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))". Target succeeded.
```

**Review by cosimon — APPROVED** [review]

**Comment by cosimon** [comment]
@pbegle Approved, if you can bring this branch up to date with the master branch I can merge the PR.

**Comment by pbegle** [comment]
Awesome, thanks @cosimon. I just updated the branch.

**Pull request merged**
